# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43af13d9abde999e6ed724fad946e3ca07a72dc9072a595cef8ed8dec2c98655a391914b5b99230077cbcb1c45aba2ba20c6f0c96333954271022d819f0da767

test:
  secret_key_base: 723172a9b9cd48e4058805c7fa4c6b816e3f7a3ba8ccc17bc10e8993187caa0c5bffaa2f5a7e3155aaa0a4df4f8a1e968117033b197f686f481bcf327490782b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
